# Generated by Django 3.1 on 2020-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200905_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='city',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default='(+254)7777422', max_length=255),
        ),
    ]
