# Generated by Django 3.1 on 2020-09-25 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, null=True)),
                ('event_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(default='WareHouse', max_length=200)),
                ('delivery_date', models.DateTimeField()),
                ('ship_to', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('On Hold', 'On Hold'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('Abandoned Cart', 'Abandoned Cart'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='New', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_option', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal'), ('Credit Card', 'Credit Card')], default='Cash On Delivery', max_length=200, null=True)),
                ('expected_delivery', models.DateTimeField(default=datetime.datetime(2020, 9, 29, 15, 25, 53, 617512), null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('order_items', models.ManyToManyField(to='orders.OrderItem')),
            ],
        ),
    ]
