# Generated by Django 3.1 on 2020-09-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
