# Generated by Django 3.1 on 2020-09-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200906_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorderitem',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
