# Generated by Django 3.1 on 2020-10-04 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201004_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_item',
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 16, 28, 36, 23446), null=True),
        ),
    ]
