# Generated by Django 3.1 on 2020-09-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200915_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
