# Generated by Django 3.1 on 2020-09-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200915_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='order_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
