# Generated by Django 3.1 on 2020-09-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200915_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='order_number',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_id',
        ),
    ]
