# Generated by Django 3.1 on 2020-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200916_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='payment_option',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal'), ('Credit Card', 'Credit Card')], default='Cash On Delivery', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal'), ('Credit Card', 'Credit Card')], default='Cash On Delivery', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('On Hold', 'On Hold'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('Abandoned Cart', 'Abandoned Cart'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='New', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('On Hold', 'On Hold'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('Abandoned Cart', 'Abandoned Cart'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='New', max_length=200, null=True),
        ),
    ]
