# Generated by Django 3.1 on 2020-09-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200917_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='order_items',
        ),
    ]
