# Generated by Django 3.1 on 2020-09-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200918_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='ordered_items', to='orders.OrderItem'),
        ),
    ]
