# Generated by Django 3.1 on 2020-09-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200918_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
    ]
