# Generated by Django 3.1 on 2020-09-18 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0022_delete_historicalorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('On Hold', 'On Hold'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('Abandoned Cart', 'Abandoned Cart'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='New', max_length=200, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('payment_option', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal'), ('Credit Card', 'Credit Card')], default='Cash On Delivery', max_length=200, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
