# Generated by Django 3.1 on 2020-09-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_historicalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
