# Generated by Django 3.1 on 2020-09-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200922_1256'),
        ('orders', '0012_auto_20200915_2226 2'),
    ]

    operations = [
    ]
